import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Morgan Wrestling | test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <div class="p-7">
        <form>
            <label class="block">
                <span class="block text-lg font-medium text-slate-700">
                    username
                </span>
                <input type="text" value="tbone" class="mt-1 block w-full px-3 py-2 bg-white border border-slate-600 rounded-md text-sm shadow-sm placeholder-slate-400
      focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500
      disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none
      invalid:border-pink-500 invalid:text-pink-600
      focus:invalid:border-pink-500 focus:invalid:ring-pink-500
      "/>
            </label>
            <button class="text-white border-slate-600 border-2 bg-slate-500 hover:bg-slate-600 m-1 px-4 py-2 rounded">
                save
            </button>
        </form>
        </div>
      </body>
    </div>
  )
}
