import Head from 'next/head'
import Image from 'next/image'
import { Box, Paper } from "@mui/material"
import CalendarComponent from '../../components/CalendarComponent'
import NavTabs from '../../components/NavTabs'



export default function CalendarPage() {
  return (
    <div>
      <Head>
        <title>Morgan Wrestling | Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavTabs tab={1} />
      <CalendarComponent />
    </div>
  )
}