import Head from 'next/head'
import { Box, Paper, Typography, Grid, Button, Divider } from "@mui/material"
import { styled } from '@mui/material/styles'
import Footer from '../../components/footer'

import { SiGuilded } from 'react-icons/si'

const Div = styled('div')(({ theme }) => ({
    ...theme.typography.body2,
}));

const TeamCommunication = () => {
    return (
        <div>
            <Head>
                <title>Morgan Wrestling | Team Communication</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Box sx={{ backgroundColor: "background.dark", p: 2 }}>
                <Grid container spacing={2} justifyContent='space-around'>
                    <Grid item xs={12}>
                        <Paper sx={{ backgroundColor: 'background.default', p: 2 }}>
                            <Typography variant='h3' sx={{ color: 'primary.main', textAlign: 'center', fontWeight: 600 }} >
                                Team Communication
                            </Typography>
                        </Paper>
                    </Grid>
                    <Grid item xs={12} md={7}>
                        <Paper sx={{ backgroundColor: 'background.default', p: 2 }}>
                            <Typography variant='h5'>New Team Communication Tool!</Typography>
                            <Divider sx={{ backgroundColor: 'primary.light', mb: 2, mt: 1 }} />

                            <Typography variant='body2'>This year we have decided to try a new communication tool!</Typography>
                            <Div>
                                <p>There are many reasons we decided to switch from the current method of communication. Rather than bore you with the thought processes of Wrestlig Coaches. We will give some goals of the new communication platform instead.</p>
                                <ol>
                                    <li>Better Overal Communication</li>
                                    <li>Less meaningless information</li>
                                    <ul>
                                        <li>Information for only Wrestlers will go to only wrestlers</li>
                                        <li>Information for only parents will only go to parents</li>
                                    </ul>
                                    <li>Dedicated Announcement Space</li>
                                    <ul>
                                        <li>No more scrolling through the chat trying to find information. Or having the same question asked multiple times</li>
                                    </ul>
                                    <li>Quicker and better responses from coaches and other parents/wrestlers</li>
                                    <ul>
                                        <li>With the new platform it will be easier to tell who a question is directed to</li>
                                        <li>It will also be easier to see when a question has been answered</li>
                                    </ul>
                                </ol>
                            </Div>
                            <Typography variant='h5'>Guilded General Information</Typography>
                            <Divider sx={{ backgroundColor: 'primary.light', mb: 2, mt: 1 }} />
                            <Div>
                                <p>The app we have chosen is called Guilded. If you haven&apos;t heard of it don&apos;t worry. It is a messaging platform designed for large group communication. Similar to Discord, Slack, or Microsoft Teams.</p>
                                <p>This app was chosen because of its large feature set. These Features include:</p>
                                <ul>
                                    <li>Calendar(s)</li>
                                    <li>Dedicated Announcement Channels</li>
                                    <li>Dedicated Chat Channels</li>
                                    <li>Its diverse chat features</li>
                                </ul>
                            </Div>
                            <Typography variant='h5'>Set-Up Instructions</Typography>                            
                            <Divider sx={{ backgroundColor: 'primary.light', mb: 2, mt: 1 }} />
                            <Div>
                                <p>At the bottom of this page there is a big Yellow button. Click on that button after you have read these instructions. It will automatically redirect you to Guilded&apos;s website</p>
                                <p>Follow these steps:</p>
                                <ol>
                                    <li>Create Account</li>
                                    <ul>
                                        <li>You will first be directed to create a Guilded account</li>
                                        <li>During the creation of your account you will be prompted to make a username <br/> (it doesn&apos;t matter what it is. But people will be able to see it if they view your profile)</li>
                                    </ul>
                                    <li>Fill out the short form</li>
                                    <ul>
                                        <li>All goofy and incomplete applications will be rejected</li>
                                        <li>The name you use as your Full Name will be set as your &apos;Nickname&apos; on the Morgan Wrestling server (group) <br/> That is the name everybody will see your posts and messages as</li>
                                    </ul>
                                    <li>Wait for your application to be approved!</li>
                                    <ul>
                                        <li>Depending on the time of day Zeth might take a few minutes to approve your application <br/> He will do it as quickly as possible</li>
                                    </ul>
                                    <li>Welcome to our New Guilded Server!</li>
                                    <ul>
                                        <li>Feel free to look around</li>
                                        <li>Within the app on the left side you will see a &apos;how-to-use&apos; item <br/> There is a detailed write up of best practices and general how to use the app tips <br/> It is highly recommended to stop by there if you haven't used an app like this before</li>
                                    </ul>
                                </ol>
                                <p>A couple last things!</p>
                                <ul>
                                    <li>Thank you for downloading another app! We know it isn&apos;t awesome to have a bunch of apps on your phone.</li>
                                    <li>If you have any questions after you have gotten in the app. Check out the &apos;how-to-use&apos; page</li>
                                    <li>YOU DO NOT NEED TO CREATE A SERVER This was already done and it is not necessary to make your own server the app may prompt you to do so</li>
                                    <li>Read these instructions before clicking the button below. It is always a pain to jump between screens when setting something up</li>
                                </ul>
                            </Div>
                        </Paper>
                    </Grid>
                    <Grid item xs={12} sx={{ textAlign: 'center' }}>
                        <Button href="https://www.guilded.gg/r/zzXENn968E?i=rdOrODy4" size='large' variant='contained' color='secondary' sx={{ color: 'primary.main', fontWeight: 600 }} startIcon={<SiGuilded />}>
                            Join Morgan Wrestling Group
                        </Button>
                    </Grid>
                </Grid>
            </Box>
            <Footer />
        </div>
    )
}

export default TeamCommunication